"""Implemented standalone controls, separate from the frozen phone/CUSTOMVIEW contract."""

GLASSDOC_OPERATION_CONTRACT = {
    "operator": "glasses",
    "physical_acceptance": "pending",
    "startup": {
        "requires_selection": True,
        "modes": ["normal", "listening"],
        "select": "swipe",
        "start": "single_tap",
        "resume": "explicit_selection",
    },
    "capture": {
        "camera_path": "camera2",
        "default": "automatic",
        "trigger": "observed_page_change_then_still",
        "ocr_characters_required": False,
        "pause_after_no_progress_seconds": 30,
        "manual_shot": "single_tap_while_waiting",
        "retake": "single_tap_during_review",
        "finish": "double_tap_after_last_visible_review",
        "review_visible_seconds": 3,
        "commit": "local_before_http",
        "camera_requests_during_review": False,
        "preview_and_saved_image_transform": "shared",
        "privacy_led": "device_controlled_no_override",
    },
    "listening": {"finish": "double_tap_in_listening_phase"},
    "answers": {
        "delivery": "answer-bundle",
        "layout": "continuous_full_answers",
        "next_previous": "swipe",
        "writing_done": "one_double_tap_then_display_sleep",
        "exit": "two_more_double_taps_within_3_seconds_while_waiting",
        "writing_done_counts_toward_exit": False,
        "offline_after_download": True,
    },
    "display_sleep": "explicit_phone_request_after_capture_writing_done_or_exit",
    "answer_wake": "active_session_and_generation_only",
    "state_notifications": "authenticated_device_session_generation_sequence",
    "unfold": "startup_chooser",
}
