"""Implemented standalone controls, separate from the frozen phone/CUSTOMVIEW contract."""

GLASSDOC_OPERATION_CONTRACT = {
    "operator": "glasses",
    "physical_acceptance": "pending",
    "startup": {
        "requires_selection": True,
        "modes": ["normal", "mixed", "listening"],
        "select": "swipe",
        "start": "single_tap",
        "resume": "explicit_selection",
        "wear_entry": "authenticated_fresh_generation_chooser_request",
    },
    "capture": {
        "camera_path": "camera2",
        "default": "automatic",
        "trigger": "observed_page_change_then_still",
        "ocr_characters_required": False,
        "pause_after_no_progress_seconds": 30,
        "manual_shot": "single_tap_while_waiting",
        "retake": "single_tap_during_review",
        "finish": "double_tap_after_last_visible_review",
        "review_visible_seconds": 3,
        "commit": "local_before_http",
        "camera_requests_during_review": False,
        "preview_and_saved_image_transform": "shared",
        "privacy_led": "device_controlled_no_override",
    },
    "listening": {"finish": "double_tap_in_listening_phase"},
    "mixed": {
        "image_analysis": "after_capture_without_waiting_for_audio",
        "audio_analysis": "same_chat_after_reading_reply_saved_and_original_audio_complete",
        "audio_dependent_before_recording": "pending_without_solution",
        "record_toggle": {
            "capturing": "swipe_either_direction",
            "photo_review": "swipe_either_direction",
            "analyzing": "single_tap",
            "waiting": "single_tap",
            "reading": "single_tap",
        },
        "reading_done": "one_double_tap_to_waiting_keep_microphone",
        "return_to_reading": "swipe_while_analyzing_or_waiting_if_saved",
        # Availability includes failed reasons; it does not assert a correct answer.
        "available_stage": "display_availability_including_failure_reasons",
    },
    "answers": {
        "delivery": "answer-bundle",
        "layout": "fixed_full_answer_slides",
        "next_previous": "swipe",
        "writing_done": "one_double_tap_then_display_sleep",
        "exit": "two_more_double_taps_within_3_seconds_while_waiting",
        "writing_done_counts_toward_exit": False,
        "offline_after_download": True,
    },
    "display_idle": {
        "seconds": 5,
        "reset_by": "user_input_only",
        "protected": ["capturing", "photo_review", "reading"],
        "request": "authenticated_display_sleep",
    },
    "display_sleep": "explicit_phone_request_for_idle_writing_done_or_exit",
    "answer_wake": "active_session_generation_and_new_answer_revision",
    "state_notifications": "authenticated_device_session_generation_sequence",
    "unfold": "startup_chooser",
}
